const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
const mentor='10000000-0000-4000-8000-000000000001',student='10000000-0000-4000-8000-000000000002';
const date=d=>{const x=new Date();x.setDate(x.getDate()-(x.getDay()+6)%7+d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const out=process.env.QA_OUTPUT || path.resolve('artifacts/catalog-qa');fs.mkdirSync(out,{recursive:true});
const db={profiles:[{id:mentor,full_name:'Mentor Teste',role:'mentor'},{id:student,full_name:'Aluna Teste',role:'student',mentor_id:mentor}],goals:[{id:'g1',student_id:student,title:'Revisão constitucional',category:'Constitucional',pillar:'leitura',due_date:date(0),completed:true,time_seconds:5400,questions_total:20,questions_correct:16,goal_blocks:[]},{id:'g2',student_id:student,title:'Leitura pendente',category:'Administrativo',pillar:'leitura',due_date:date(0),completed:false,time_seconds:0,goal_blocks:[]},{id:'g3',student_id:student,title:'Planejamento futuro',category:'Civil',pillar:'leitura',due_date:date(6),completed:false,time_seconds:0,goal_blocks:[]}],exam_history:[],goal_templates:[],goal_week_packs:[],goal_blocks:[]};let count=0;const imported=new Set();
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const context=await browser.newContext({viewport:{width:1600,height:1050}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
let failTemplateWrite=false;
await context.route('https://*.supabase.co/**',async route=>{
 const req=route.request(),url=new URL(req.url()),table=url.pathname.split('/').pop();
 if(url.pathname.includes('/auth/'))return route.fulfill({json:{}});
 if(!url.pathname.includes('/rest/v1/'))return route.abort();
 const payload=req.postDataJSON();const single=(req.headers().accept || '').includes('vnd.pgrst.object');
 if(table==='goal_templates' && req.method()==='POST' && failTemplateWrite){failTemplateWrite=false;return route.fulfill({status:500,json:{message:'Falha simulada no catálogo'}})}
 const respond=data=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(single?data[0]:data)});
 if(table==='import_goal_week_pack'){
   const key=JSON.stringify(payload);if(imported.has(key))return route.fulfill({status:400,json:{message:'Este pacote já foi importado para este aluno nesta semana.'}});
   imported.add(key);const p=db.goal_week_packs.find(p=>p.id===payload.p_pack);
   for(const it of p.items){const t=db.goal_templates.find(t=>t.id===it.template_id);const d=new Date(payload.p_week+'T12:00:00');d.setDate(d.getDate()+it.weekday);db.goals.push({id:'new'+(++count),student_id:payload.p_student,title:t.title,category:t.category,pillar:t.pillar,activity_type:t.activity_type,topic:t.topic,material_url:t.material_url,teacher_notes:t.teacher_notes,due_date:d.toISOString().slice(0,10),completed:false,time_seconds:0,questions_total:null,questions_correct:null,goal_blocks:[]})}
   return route.fulfill({json:p.items.length});
 }
 if(!db[table])throw Error('Unexpected table '+table);
 let rows=db[table].filter(row=>[...url.searchParams].every(([key,val])=>val.startsWith('eq.')?String(row[key])===val.slice(3):val.startsWith('in.')?val.slice(4,-1).split(',').includes(row[key]):true));
 if(req.method()==='POST'){const list=Array.isArray(payload)?payload:[payload];rows=list.map(p=>{const existing=p.id && db[table].find(r=>r.id===p.id);if(existing && req.headers().prefer?.includes('merge-duplicates'))return Object.assign(existing,p);const row={id:'new'+(++count),completed:false,time_seconds:0,goal_blocks:[],...p};db[table].push(row);return row})}
 if(req.method()==='PATCH')rows.forEach(r=>Object.assign(r,payload));
 return respond(rows);
});
async function refocusAndRefresh(label,expected){
 const before=await page.getByLabel(label,{exact:true}).elementHandle();
 await page.evaluate(async()=>{
  const {supabase}=await import('/src/supabaseClient.js');
  const {data:{session}}=await supabase.auth.getSession();
  document.dispatchEvent(new Event('visibilitychange'));
  await supabase.auth._notifyAllSubscribers('SIGNED_IN',structuredClone(session));
  await supabase.auth._notifyAllSubscribers('TOKEN_REFRESHED',structuredClone(session));
 });
 await page.waitForTimeout(250);
 assert.equal(await before.evaluate(el=>el.isConnected),true,'Form must remain mounted');
 assert.equal(await page.getByLabel(label,{exact:true}).inputValue(),expected);
}
async function login(id){await page.addInitScript(({id,mentor})=>{id=localStorage.getItem('qa-user') || id;const session={access_token:'eyJhbGciOiJIUzI1NiJ9.'+btoa(JSON.stringify({sub:id,exp:2100000000}))+'.test',refresh_token:'test',expires_at:2100000000,expires_in:3600,token_type:'bearer',user:{id,email:id===mentor?'mentor@test.local':'student@test.local',aud:'authenticated',role:'authenticated'}};localStorage.setItem('sb-dgkftixzeudmvmdfcrwu-auth-token',JSON.stringify(session))},{id,mentor})}
await login(mentor);await page.goto('http://127.0.0.1:5191/mentor/metas');
await page.getByText('Selecione um aluno acima para visualizar e editar suas metas.').waitFor();
assert.equal(await page.locator('.weekly-calendar').count(),0);assert.equal(await page.getByLabel('Buscar aluno ou meta').count(),0);
for(const label of ['Copiar semana anterior','Usar meta como modelo','Editar em lote'])assert.equal(await page.getByRole('button',{name:label,exact:true}).count(),0);
await page.screenshot({path:path.join(out,'select-student.png'),fullPage:true});
await page.goto('http://127.0.0.1:5191/mentor/catalogo');
await page.getByRole('button',{name:'＋ Nova meta padrão',exact:true}).click();
await page.getByLabel('Matéria',{exact:true}).fill('Constitucional');await page.getByLabel('Assunto',{exact:true}).fill('Direitos fundamentais');await page.getByLabel('Categoria',{exact:true}).selectOption('revisao');
await page.getByLabel('Observações do professor',{exact:true}).fill('Leia os artigos indicados.\nAnote suas dúvidas.');await refocusAndRefresh('Observações do professor','Leia os artigos indicados.\nAnote suas dúvidas.');await page.getByLabel('Link do Material',{exact:true}).fill('https://example.com/material');assert.equal(await page.getByLabel('Título da meta').count(),0);assert.deepEqual(await page.getByLabel('Categoria',{exact:true}).locator('option').allTextContents(),['Teoria','Revisão','Questões','Legislação','Jurisprudência','Outros']);await page.getByRole('button',{name:'Salvar no catálogo'}).click();await page.getByText('Meta padrão salva no catálogo.').waitFor();assert.equal(db.goal_templates.length,1);assert.equal(db.goal_templates[0].teacher_notes,'Leia os artigos indicados.\nAnote suas dúvidas.');
await page.getByLabel('Buscar no catálogo').fill('Direitos');await page.getByText('1 metas · 1 assuntos').waitFor();await page.screenshot({path:path.join(out,'catalog.png'),fullPage:true});
await page.goto('http://127.0.0.1:5191/mentor/pacotes');await page.getByRole('button',{name:'＋ Novo pacote'}).click();await page.getByLabel('Nome do pacote').fill('Semana 1 — Fundamentos');await page.getByLabel('Adicionar meta em Segunda',{exact:true}).selectOption(db.goal_templates[0].id);await page.getByLabel('Adicionar meta em Quinta',{exact:true}).selectOption(db.goal_templates[0].id);await page.screenshot({path:path.join(out,'pack-editor.png'),fullPage:true});await page.getByRole('button',{name:'Salvar pacote'}).click();await page.getByText('Pacote semanal salvo.').waitFor();assert.equal(db.goal_week_packs[0].items.length,2);
await page.getByRole('link',{name:'Importar para aluno'}).click();await page.getByLabel('Aluno',{exact:true}).selectOption(student);await page.getByRole('button',{name:'Importar pacote para esta semana',exact:true}).click();await page.getByText('2 metas importadas.').waitFor();assert.equal(db.goals.length,5);assert.equal(db.goals[3].teacher_notes,db.goal_templates[0].teacher_notes);
await page.locator('.calendar-goal.done').waitFor();assert.equal(await page.locator('.calendar-goal.done').count(),1);assert.equal(await page.locator('.calendar-goal.late').count(),db.goals.filter(g=>!g.completed && g.due_date<new Date().toLocaleDateString('en-CA')).length);await page.getByText('Tempo total: 1h 30min').waitFor();await page.getByText('80% de acertos').waitFor();
await page.getByRole('button',{name:'Importar pacote semanal',exact:true}).click();await page.getByRole('button',{name:'Importar pacote para esta semana',exact:true}).click();await page.getByText('Este pacote já foi importado para este aluno nesta semana.').waitFor();assert.equal(db.goals.length,5);assert.equal(db.goals[3].teacher_notes,db.goal_templates[0].teacher_notes);await page.getByRole('button',{name:'Fechar',exact:true}).click();
await page.getByRole('button',{name:'Revisão constitucional',exact:true}).click();
assert.equal(await page.getByLabel('Assunto',{exact:true}).inputValue(),'Revisão constitucional');for(const label of ['Título da meta','Horas estudadas','Minutos estudados','Questões respondidas','Acertos','Nome do bloco'])assert.equal(await page.getByLabel(label,{exact:true}).count(),0);
await page.getByLabel('Observações do professor',{exact:true}).fill('Revisar antes das questões.');await refocusAndRefresh('Observações do professor','Revisar antes das questões.');await page.getByLabel('Categoria',{exact:true}).selectOption('revisao');await page.getByLabel('Link do Material',{exact:true}).fill('https://example.com/revisao');await page.getByRole('button',{name:'Salvar alterações'}).click();await page.getByText('Meta salva com sucesso.').waitFor();assert.equal(db.goals[0].time_seconds,5400);assert.equal(db.goals[0].questions_correct,16);assert.equal(db.goals[0].questions_total,20);assert.equal(db.goals[0].completed,true);assert.equal(db.goals[0].activity_type,'revisao');assert.equal(db.goals[0].material_url,'https://example.com/revisao');
await page.locator('.calendar-day').nth(2).getByRole('button',{name:'＋ Adicionar meta'}).click();
await page.getByRole('dialog',{name:'Adicionar meta'}).waitFor();assert.equal(await page.locator('.goal-editor').count(),0);assert.equal(await page.getByLabel('Dia da meta').inputValue(),date(2));
await page.getByLabel('Buscar no catálogo',{exact:true}).fill('zzzzz');await page.getByText('Nenhuma meta encontrada neste filtro.').waitFor();await page.getByLabel('Buscar no catálogo',{exact:true}).fill('fundamentais');await page.getByLabel('Filtrar matéria').selectOption('Constitucional');
await page.screenshot({path:path.join(out,'inline-goal-picker.png'),fullPage:true});
await page.getByRole('button',{name:'Importar Direitos fundamentais',exact:true}).click();await page.getByText('Meta importada para Aluna Teste.').waitFor();assert.equal(db.goals.length,6);assert.equal(db.goals[5].due_date,date(2));assert.equal(db.goals[5].teacher_notes,db.goal_templates[0].teacher_notes);assert.equal(await page.locator('.goal-editor').count(),0);
await page.getByLabel('Selecionar Revisão constitucional',{exact:true}).check();await page.getByLabel('Nova data',{exact:true}).waitFor();assert.equal(await page.getByLabel('Nova data',{exact:true}).inputValue(),date(0));await page.getByLabel('Selecionar Revisão constitucional',{exact:true}).uncheck();assert.equal(await page.getByLabel('Nova data',{exact:true}).count(),0);
await page.getByLabel('Selecionar Leitura pendente',{exact:true}).check();await page.getByLabel('Selecionar Planejamento futuro',{exact:true}).check();await page.getByLabel('Nova data',{exact:true}).fill(date(5));await page.getByRole('button',{name:'Aplicar data',exact:true}).click();await page.getByText('2 metas reagendadas.').waitFor();assert.equal(db.goals[1].due_date,date(5));assert.equal(db.goals[2].due_date,date(5));assert.equal(db.goals[0].due_date,date(0));
async function createManual(title,catalogued){
 await page.locator('.calendar-day').nth(4).getByRole('button',{name:'＋ Adicionar meta'}).click();await page.getByRole('button',{name:'＋ Criar outra meta'}).click();await page.getByLabel('Assunto',{exact:true}).fill(title);await page.getByLabel('Matéria',{exact:true}).fill('Civil');assert.equal(await page.getByLabel('Prazo',{exact:true}).count(),0);
 if(catalogued){await page.getByLabel('Também incluir esta meta no catálogo').check();await page.getByLabel('Categoria',{exact:true}).selectOption('outros');}
 await page.getByRole('button',{name:'Salvar alterações'}).click();await page.getByText(catalogued?'Meta salva para o aluno e incluída no catálogo.':'Meta salva com sucesso.').waitFor();
}
await createManual('Somente para esta aluna',false);assert.equal(db.goal_templates.length,1);assert.equal(db.goal_templates[0].teacher_notes,'Leia os artigos indicados.\nAnote suas dúvidas.');assert.equal(db.goals.length,7);
await createManual('Contratos civis',true);assert.equal(db.goal_templates.length,2);assert.equal(db.goals.length,8);assert.equal(db.goal_templates[1].topic,'Contratos civis');assert.equal(db.goal_templates[1].activity_type,'outros');assert.equal(db.goal_templates[1].blocks.length,0);assert.equal(db.goal_templates[1].title,'Contratos civis');
await page.locator('.calendar-day').nth(4).getByRole('button',{name:'＋ Adicionar meta'}).click();await page.getByRole('button',{name:'＋ Criar outra meta'}).click();await page.getByLabel('Assunto',{exact:true}).fill('Meta com nova tentativa');await page.getByLabel('Matéria',{exact:true}).fill('Civil');await page.getByLabel('Também incluir esta meta no catálogo').check();failTemplateWrite=true;await page.getByRole('button',{name:'Salvar alterações'}).click();await page.getByText(/A meta já existe, mas o salvamento não terminou/).waitFor();assert.equal(db.goals.length,9);assert.equal(db.goal_templates.length,2);await page.getByRole('button',{name:'Salvar alterações'}).click();await page.getByText('Meta salva para o aluno e incluída no catálogo.').waitFor();assert.equal(db.goals.length,9);assert.equal(db.goal_templates.length,3);
await page.getByLabel('Selecionar Revisão constitucional',{exact:true}).check();await page.getByLabel('Aluno',{exact:true}).selectOption('');await page.getByText('Selecione um aluno acima para visualizar e editar suas metas.').waitFor();assert.equal(await page.locator('.weekly-calendar').count(),0);assert.equal(await page.getByLabel('Nova data',{exact:true}).count(),0);await page.getByLabel('Aluno',{exact:true}).selectOption(student);await page.locator('.weekly-calendar').waitFor();assert.equal(await page.getByLabel('Selecionar Revisão constitucional',{exact:true}).isChecked(),false);
await page.screenshot({path:path.join(out,'mentor-calendar.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'mobile-calendar.png'),fullPage:true});
await page.evaluate(id=>localStorage.setItem('qa-user',id),student);
await page.setViewportSize({width:1400,height:950});await page.goto('http://127.0.0.1:5191/semana');
await page.locator('.calendar-goal.done').waitFor();assert.equal(await page.getByRole('link',{name:'Catálogo de metas'}).count(),0);
await page.getByRole('link',{name:'Revisão constitucional',exact:true}).click();
await page.getByText('Revisar antes das questões.',{exact:true}).waitFor();await page.getByRole('button',{name:'Editar tempo e resultados'}).click();await page.getByLabel('Horas estudadas').fill('1');await refocusAndRefresh('Horas estudadas','1');await page.getByLabel('Minutos estudados').fill('40');await page.getByLabel('Questões respondidas').fill('20');await page.getByLabel('Acertos',{exact:true}).fill('21');await page.getByRole('button',{name:'Salvar registro'}).click();await page.getByText('Informe questões e acertos; os acertos não podem superar as questões.').waitFor();assert.equal(db.goals[0].time_seconds,5400);
await page.getByLabel('Acertos',{exact:true}).fill('15');await page.getByRole('button',{name:'Salvar registro'}).click();await page.getByText('Registro do estudo salvo.').waitFor();assert.equal(db.goals[0].time_seconds,6000);assert.equal(db.goals[0].questions_correct,15);
await page.getByRole('button',{name:'Iniciar',exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Editar tempo e resultados' && b.disabled));assert.equal(await page.getByRole('button',{name:'Editar tempo e resultados'}).isEnabled(),false);await page.waitForTimeout(2200);await page.getByRole('button',{name:'Pausar',exact:true}).click();await page.getByRole('button',{name:'Editar tempo e resultados'}).waitFor();await page.waitForFunction(()=>!document.querySelector('fieldset[disabled]'));assert.ok(db.goals[0].time_seconds>=6002);
await page.screenshot({path:path.join(out,'student-results.png'),fullPage:true});
await page.evaluate(async mentor=>{const {supabase}=await import('/src/supabaseClient.js');const {data:{session}}=await supabase.auth.getSession();await supabase.auth._notifyAllSubscribers('SIGNED_IN',{...session,user:{...session.user,id:mentor}})},mentor);await page.getByText('PAINEL DO PROFESSOR',{exact:true}).waitFor();await page.evaluate(async()=>{const {supabase}=await import('/src/supabaseClient.js');await supabase.auth._notifyAllSubscribers('SIGNED_OUT',null)});await page.waitForURL('**/login');
assert.deepEqual(errors,[]);console.log('PASS: catalog CRUD, packs, import/duplicate, calendar states/metrics, mentor time/results, catalog-to-day, mobile, student results validation/save and stopwatch.');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
