import { useEffect, useRef, useState } from 'react'
import { addDays } from 'date-fns'
import { supabase } from '../supabaseClient'
import { dateKey } from './WorkspaceUI'
import GoalResultsFields, { resultsPayload } from './GoalResultsFields'
import { activityKey, pillarOf } from '../lib/pillars'
export default function StudyCompletionModal({goal,onClose,onSaved,complete=true}){
 const [form,setForm]=useState({...goal,study_date:dateKey(),student_notes:'',material:''}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const dialog=useRef(null),request=useRef(crypto.randomUUID())
 useEffect(()=>{const previous=document.activeElement;dialog.current?.focus();const close=e=>{if(e.key==='Escape'&&!busy)onClose();if(e.key==='Tab'){const nodes=[...dialog.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')];if(!nodes.length)return;if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0].focus()}}};document.addEventListener('keydown',close);return()=>{document.removeEventListener('keydown',close);previous?.focus()}},[busy,onClose])
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const p=resultsPayload(form);const {data,error}=await supabase.rpc('record_goal_study',{p_goal:goal.id,p_date:form.study_date,p_seconds:p.time_seconds,p_total:p.questions_total,p_correct:p.questions_correct,p_complete:complete,p_request:request.current,p_expected:goal.time_seconds,p_notes:form.student_notes,p_material:form.material});if(error)throw error;onSaved(data);onClose()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="study-modal-backdrop"><section className="study-modal" role="dialog" aria-modal="true" aria-labelledby="study-record-title" tabIndex={-1} ref={dialog}><div className="card-heading"><h2 id="study-record-title">Registro de estudo</h2><button className="btn" aria-label="Fechar registro" disabled={busy} onClick={onClose}>×</button></div>
 <form onSubmit={save}><fieldset disabled={busy} className="editor-fields"><div className="toolbar"><button type="button" className="btn" onClick={()=>setForm({...form,study_date:dateKey()})}>Hoje</button><button type="button" className="btn" onClick={()=>setForm({...form,study_date:dateKey(addDays(new Date(),-1))})}>Ontem</button><label>Data do estudo<input required className="field" type="date" max={dateKey()} value={form.study_date} onChange={e=>setForm({...form,study_date:e.target.value})}/></label></div>
 <div className="field-grid"><label>Categoria<select className="field" aria-label="Categoria" value={activityKey(goal)} disabled><option value={activityKey(goal)}>{pillarOf(activityKey(goal)).label}</option></select></label><label>Matéria<select className="field" aria-label="Matéria" value={goal.category} disabled><option>{goal.category}</option></select></label></div><label>Assunto<select className="field" aria-label="Assunto" value={goal.topic||goal.title} disabled><option>{goal.topic||goal.title}</option></select></label><p className="muted small">Dados da meta definidos pelo professor a partir do edital.</p>
 <GoalResultsFields value={form} onChange={setForm}/><label>Material estudado<input className="field" value={form.material} placeholder="Ex.: aula 01 ou capítulo 3" onChange={e=>setForm({...form,material:e.target.value})}/></label><label>Comentários<textarea aria-label="Comentários" className="field" rows={3} value={form.student_notes} onChange={e=>setForm({...form,student_notes:e.target.value})}/></label>
 {error&&<p className="notice error" role="alert">{error}</p>}<div className="editor-footer"><button type="button" className="btn" onClick={onClose}>Cancelar</button><button className="btn primary">{busy?'Salvando…':complete?'Salvar e concluir meta':'Salvar registro'}</button></div></fieldset></form></section></div>
}
